import os
import sys
import sipconfig
from PyQt5.QtCore import PYQT_CONFIGURATION as pyqtconf
     
basename = sys.argv[1]

     
# The name of the SIP build file generated by SIP and used by the build
# system.
build_file = basename + ".sbf"
     
# Get the SIP configuration information.
config = sipconfig.Configuration()

# pyqt config for PyQt5 :
pyqt_flags = pyqtconf['sip_flags']


# clean build dir :
#filelist = [ f for f in os.listdir(build_path) ]
#for f in filelist:
#    os.remove(f)

# Run SIP to generate the code.
os.system(" ".join([config.sip_bin, "-c", "./", "-I", "/usr/share/sip/PyQt5", pyqt_flags, "-b", build_file, basename + ".sip"]))
     
# Create the Makefile.
makefile = sipconfig.SIPModuleMakefile(config, build_file)

     
# Add the library we are wrapping.  The name doesn't include any platform
# specific prefixes or extensions (e.g. the "lib" prefix on UNIX, or the
# ".dll" extension on Windows).
makefile.extra_libs = ["plume-creator-data"]

								# for ubuntu 16.4 x86_64 and
makefile.extra_include_dirs = ["/usr/include/x86_64-linux-gnu/qt5", "/usr/include/x86_64-linux-gnu/qt5/QtCore", \
								# for fedora 24
								"/usr/include/qt5", "/usr/include/qt5/QtCore"]
makefile.extra_lib_dirs = ["."]
     
# Search libraries in current directory
makefile.extra_lflags= ['-L.']

#makefile.extra_lflags= ['DESTDIR=' + build_path]

# Generate the Makefile itself.
makefile.generate()
